/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Equipo;
import clases.Item;
import clases.Proyecto;
import clases.TipoItem;
import clases.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import programa.generadorProyectos;
import programa.generadorUsuarios;

/**
 *
 * @author Chino
 */
public class CrearItemDialog extends javax.swing.JDialog {

    private Equipo equipoItem;
    private Proyecto proyectoActual;
    /**
     * Creates new form CrearItemDialog
     * @param parent
     * @param modal
     */
    
    public CrearItemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarElementos();
    }

     public CrearItemDialog (java.awt.Frame parent, boolean modal,Proyecto proyectoActual){
         super(parent,modal);
         initComponents();
         this.proyectoActual = proyectoActual;
         this.equipoItem = this.proyectoActual.getEquipo();
         cargarElementos();
     }
     
     public void setProyecto(Proyecto proyectoActual){
         this.proyectoActual = proyectoActual;
         this.equipoItem = this.proyectoActual.getEquipo();
     }
     
     private void cargarElementos(){
         // primero se cargan los tipos de item disponibles
            ArrayList<TipoItem> tiposItemDisponibles =  generadorProyectos.getTiposItem();
            DefaultListModel<String> dlm = new DefaultListModel();
            for(TipoItem t:tiposItemDisponibles){
                  dlm.addElement(t.getNombre());
            }
                  jListTiposItemDisponibles.setModel(dlm);
         /* luego los integrantes del equipo que esté trabajando con el proyecto para
            ser los responsables */
           ArrayList<Usuario> posiblesResponsables = equipoItem.getIntegrantes();
                  dlm = new DefaultListModel();
           for(Usuario u:posiblesResponsables){
                  dlm.addElement(u.getNombre());
           }      
               jListPosiblesResponsables.setModel(dlm);
               
               jComboBoxPrioridad.addItem("BAJA");
               jComboBoxPrioridad.addItem("MEDIA");
               jComboBoxPrioridad.addItem("ALTA");
               
               jLabelValidarDatos.setForeground(Color.red);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreItem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTiposItemDisponibles = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPosiblesResponsables = new javax.swing.JList<>();
        jButtonCrearItem = new javax.swing.JButton();
        jLabelValidarDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Item");

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("Crear Item");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Tipo de Item");

        jScrollPane1.setViewportView(jListTiposItemDisponibles);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prioridad");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Responsable");

        jScrollPane2.setViewportView(jListPosiblesResponsables);

        jButtonCrearItem.setText("Crear");
        jButtonCrearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearItemActionPerformed(evt);
            }
        });

        jLabelValidarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextFieldNombreItem)
                                    .addComponent(jComboBoxPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButtonCrearItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelValidarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabelValidarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearItem)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearItemActionPerformed
        // TODO add your handling code here:
        // se deben validar los datos, por ejemplo, que el item no tenga el mismo nombre
         String nombreNuevoItem = jTextFieldNombreItem.getText();
           if ((nombreNuevoItem.isEmpty())|(jListTiposItemDisponibles.getSelectedIndex()<0)|(jComboBoxPrioridad.getSelectedIndex()<0)|(jListPosiblesResponsables.getSelectedIndex()<0)){
               jLabelValidarDatos.setText("Debe completar los campos");
           }else
               // el nombre no puede ser igual sólamente dentro del proyecto
               if(proyectoActual.getItem(nombreNuevoItem) != null){
                  JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this),"Ya existe un item con ese nombre dentro del proyecto"); 
               }
               else{
                  // se busca al frame padre para poder conseguir el usuario que está utilizando el programa 
                  FramePrincipal frameActual = (FramePrincipal)SwingUtilities.getWindowAncestor(this);
                  Usuario uL = frameActual.getUsuarioLogueado();
                  
                  String nombreTipo = jListTiposItemDisponibles.getSelectedValue();
                  String prioridadNuevoItem = (String)jComboBoxPrioridad.getSelectedItem();
                  TipoItem tipoSeleccionado = generadorProyectos.getTipoItem(nombreTipo);
                  Item nuevoItemCreado = new Item(nombreNuevoItem,tipoSeleccionado,prioridadNuevoItem,uL);
                          nuevoItemCreado.setResponsable(generadorUsuarios.getUsuario(jListPosiblesResponsables.getSelectedValue()));
                          proyectoActual.addItem(nuevoItemCreado);
                  JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this),"Se ha creado el item exitosamente");
                  jTextFieldNombreItem.setText("");
                  jListTiposItemDisponibles.setSelectedIndex(0);
                  jComboBoxPrioridad.setSelectedIndex(0);
                  jListPosiblesResponsables.setSelectedIndex(0);
               }
    }//GEN-LAST:event_jButtonCrearItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearItemDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearItemDialog dialog = new CrearItemDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearItem;
    private javax.swing.JComboBox<String> jComboBoxPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelValidarDatos;
    private javax.swing.JList<String> jListPosiblesResponsables;
    private javax.swing.JList<String> jListTiposItemDisponibles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldNombreItem;
    // End of variables declaration//GEN-END:variables
}
