/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Estado;
import clases.Item;
import clases.Proyecto;
import clases.TipoItem;
import clases.Usuario;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import programa.generadorProyectos;
import programa.generadorUsuarios;

/**
 *
 * @author Chino
 */
public class ItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemPanel
     */
    
    private Proyecto proyectoItems;
    private Item itemSeleccionado;
    
    public ItemPanel(){
        initComponents();
    }

    public ItemPanel(Proyecto proyecto){
         initComponents();
         setProyecto(proyecto);
    }
    
    public void setProyecto(Proyecto proyecto){
         proyectoItems = proyecto;
         cargarElementos();
    }
    
    private void cargarElementos(){
         
         jLabelNombreProyecto.setText(proyectoItems.getNombre());
        
         DefaultListModel<String> dlm = new DefaultListModel<>(); 
         
                  for(Item it:proyectoItems.getItems()){
                           if(it == null)
                                    System.out.println("ITEM NULO");
                           else
                                    dlm.addElement(it.getNombre());
                           
                  }
                  
         jListItems.setModel(dlm);
         jButtonPrioridad.setEnabled(false);
         jButtonEstado.setEnabled(false);
         jButtonResponsable.setEnabled(false);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItems = new javax.swing.JList<>();
        jButtonCrearItem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreItem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabelTipoItem = new javax.swing.JLabel();
        jButtonHistoriales = new javax.swing.JButton();
        jLabelPrioridad = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelResponsable = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxPrioridad = new javax.swing.JComboBox<>();
        jButtonPrioridad = new javax.swing.JButton();
        jButtonEstado = new javax.swing.JButton();
        jComboBoxEstados = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxMiembros = new javax.swing.JComboBox<>();
        jButtonResponsable = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelNombreProyecto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 13))); // NOI18N

        jListItems.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jListItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListItems);

        jButtonCrearItem.setText("Nuevo Item");
        jButtonCrearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jButtonCrearItem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearItem)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 13))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre Completo ");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Prioridad");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estado Actual");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Responsable");

        jTextFieldNombreItem.setEditable(false);
        jTextFieldNombreItem.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tipo de Item");

        jLabelTipoItem.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jButtonHistoriales.setText("Historial");
        jButtonHistoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistorialesActionPerformed(evt);
            }
        });

        jLabelPrioridad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabelEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabelResponsable.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("Modificar Información");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel10.setText("Prioridad");

        jButtonPrioridad.setText("Cambiar");
        jButtonPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrioridadActionPerformed(evt);
            }
        });

        jButtonEstado.setText("Cambiar");
        jButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel13.setText("Estado");

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel14.setText("Responsable");

        jButtonResponsable.setText("Cambiar");
        jButtonResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResponsableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelPrioridad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTipoItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jButtonHistoriales, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombreItem)
                            .addComponent(jLabelEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBoxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jComboBoxMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(94, 94, 94))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPrioridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonHistoriales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPrioridad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMiembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonResponsable))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("Proyecto: ");

        jLabelNombreProyecto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabelNombreProyecto.setText("Nombre Proyecto");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bullet-list64.png"))); // NOI18N
        jLabel12.setText(" Items");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNombreProyecto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHistorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistorialesActionPerformed
        // TODO add your handling code here:
        if(jListItems.getSelectedIndex() > -1){
           JFrame f1 = (JFrame) SwingUtilities.windowForComponent(this);
           HistorialItemDialog hid = new HistorialItemDialog(f1,true);
                                   hid.setItem(proyectoItems.getItem(jListItems.getSelectedValue()));
                                   hid.setLocationRelativeTo(this);
                                   hid.setVisible(true);
        }else{
           JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Seleccione un item de la lista");
        }

    }//GEN-LAST:event_jButtonHistorialesActionPerformed

    private void jButtonCrearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearItemActionPerformed
        // TODO add your handling code here:
       JFrame f1 = (JFrame) SwingUtilities.windowForComponent(this);
       CrearItemDialog cid = new CrearItemDialog(f1,true,proyectoItems);
                               cid.setLocationRelativeTo(this);
                               cid.setVisible(true);
                              
        // cuando se cierre, se debería actualizar la lista de items disponibles
          cargarElementos();
    }//GEN-LAST:event_jButtonCrearItemActionPerformed

    private void jListItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListItemsMouseClicked
         // TODO add your handling code here:
         
         jComboBoxPrioridad.removeAllItems();
         jComboBoxPrioridad.addItem("ALTA");
         jComboBoxPrioridad.addItem("MEDIA");
         jComboBoxPrioridad.addItem("BAJA");
         
         String nombreItemSeleccionado = jListItems.getSelectedValue();
         itemSeleccionado = proyectoItems.getItem(nombreItemSeleccionado);
         
         // se carga la información para mostrarla al usuario
         jTextFieldNombreItem.setText(nombreItemSeleccionado);    
         jLabelPrioridad.setText(itemSeleccionado.getPrioridad());
         jLabelEstado.setText(itemSeleccionado.getEstadoActual().getEstado());
         jLabelTipoItem.setText(itemSeleccionado.getTipo().getNombre());
                 
         // cargar los miembros de equipo disponibles y posicionar el actual en la comboBox
         jComboBoxMiembros.removeAllItems();
         ArrayList <Usuario> miembrosDisponibles = proyectoItems.getEquipo().getIntegrantes();
         Usuario responsableItem = itemSeleccionado.getResponsable();
         
                  if(responsableItem == null){
                           jLabelResponsable.setText("Sin Responsable");
                           jComboBoxMiembros.addItem("Seleccione un miembro de equipo");
                  }else{
                           jLabelResponsable.setText(itemSeleccionado.getResponsable().getNombre());
                           jComboBoxMiembros.setSelectedItem(responsableItem.getNombre());
                  }
                           
                  for(Usuario u:miembrosDisponibles){
                           jComboBoxMiembros.addItem(u.getNombre());
                  }
                  
         // cargar los miembros disponibles y posicionar el responsable en la comboBox
         jComboBoxEstados.removeAllItems();
         // se procede a cargar los posibles estados que puede tomar el item
         ArrayList<Estado> est = itemSeleccionado.getTipo().getEstadosSiguientes(itemSeleccionado.getEstadoActual());
         
                  for(Estado e:est){
                           jComboBoxEstados.addItem(e.getEstado());
                  }         
                           jComboBoxEstados.setSelectedItem(itemSeleccionado.getEstadoActual().getEstado());
            
         jLabelTipoItem.setText(itemSeleccionado.getTipo().getNombre());
        
                  if(itemSeleccionado.getPrioridad() != null){
                           if(itemSeleccionado.getPrioridad().equals("ALTA")){
                                     jComboBoxPrioridad.setSelectedIndex(0);
                           }else if(itemSeleccionado.getPrioridad().equals("MEDIA")){
                                    jComboBoxPrioridad.setSelectedIndex(1);
                           }else{
                                    jComboBoxPrioridad.setSelectedIndex(2);
                  }
         } 
                  
         jButtonPrioridad.setEnabled(true);
         jButtonEstado.setEnabled(true);
         jButtonResponsable.setEnabled(true);
         
    }//GEN-LAST:event_jListItemsMouseClicked

    private void jButtonPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrioridadActionPerformed
        // TODO add your handling code here:
         itemSeleccionado.setPrioridad((String)jComboBoxPrioridad.getSelectedItem());
         jComboBoxPrioridad.setSelectedItem(itemSeleccionado.getPrioridad());
         JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Prioridad Cambiada");
         jLabelEstado.setText(itemSeleccionado.getPrioridad());
    }//GEN-LAST:event_jButtonPrioridadActionPerformed

    private void jButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadoActionPerformed
        // TODO add your handling code here:
         String nombreNuevoEstado = (String) jComboBoxEstados.getSelectedItem();

                  if (!(itemSeleccionado.getEstadoActual().getEstado().equals(nombreNuevoEstado))){
                           Estado nuevoEstado = itemSeleccionado.getTipo().getEstado(nombreNuevoEstado);
                           itemSeleccionado.cambiarEstado(nuevoEstado);
                           jComboBoxEstados.setSelectedItem(nombreNuevoEstado);
                           jLabelEstado.setText(nuevoEstado.getEstado());
                  }
         
        JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Estado Cambiado");
    }//GEN-LAST:event_jButtonEstadoActionPerformed

    private void jButtonResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResponsableActionPerformed
        // TODO add your handling code here:
         String responsableSeleccionado = (String) jComboBoxMiembros.getSelectedItem();
         boolean responsableModificado = false;
         
         if(itemSeleccionado.getResponsable() == null){
                  Usuario nuevoResponsable = generadorUsuarios.getUsuario(responsableSeleccionado);
                  itemSeleccionado.setResponsable(nuevoResponsable);
                  jComboBoxMiembros.removeItemAt(0);
                  jComboBoxMiembros.setSelectedItem(responsableSeleccionado);
                  responsableModificado = true;
         }else{
                  if (!(itemSeleccionado.getResponsable().getNombre().equals(responsableSeleccionado))){
                           Usuario nuevoResponsable = generadorUsuarios.getUsuario(responsableSeleccionado);
                           itemSeleccionado.setResponsable(nuevoResponsable);
                           jComboBoxMiembros.setSelectedItem(responsableSeleccionado);
                           responsableModificado = true;
                  }
         }
                  JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Responsable Cambiado");

         if(responsableModificado){
                  jLabelResponsable.setText(responsableSeleccionado);
         }
    }//GEN-LAST:event_jButtonResponsableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearItem;
    private javax.swing.JButton jButtonEstado;
    private javax.swing.JButton jButtonHistoriales;
    private javax.swing.JButton jButtonPrioridad;
    private javax.swing.JButton jButtonResponsable;
    private javax.swing.JComboBox<String> jComboBoxEstados;
    private javax.swing.JComboBox<String> jComboBoxMiembros;
    private javax.swing.JComboBox<String> jComboBoxPrioridad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombreProyecto;
    private javax.swing.JLabel jLabelPrioridad;
    private javax.swing.JLabel jLabelResponsable;
    private javax.swing.JLabel jLabelTipoItem;
    private javax.swing.JList<String> jListItems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombreItem;
    // End of variables declaration//GEN-END:variables
}
