/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Proyecto;
import clases.Usuario;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import programa.generadorProyectos;
import programa.generadorUsuarios;

/**
 * 
 * @author Chino
 */
public class ProyectoPanel extends javax.swing.JPanel {

     private ArrayList<Proyecto> proyectos;
     private Proyecto proyectoSeleccionado;
     private ArrayList<Usuario> lideres;
    /**
     * Creates new form ProyectoPanel
     */
     
    public ProyectoPanel() {
        initComponents();
        jButtonVerItems.setEnabled(false);
    }
    
    public ProyectoPanel(ArrayList<Proyecto> proyectosCarga, ArrayList<Usuario> lideresCarga){
        initComponents();
        jButtonVerItems.setEnabled(false);
        setProyectos(proyectosCarga);
        setLideres(lideresCarga);
    } 
            
    public void setProyectos(ArrayList<Proyecto> proyectosCargar){
        
         jComboBoxProyectos.removeAllItems();
         jComboBoxProyectos.addItem("Seleccione un proyecto");
         this.proyectos = proyectosCargar;
        
         for(Proyecto p:proyectos){
                   jComboBoxProyectos.addItem(p.getNombre());
         }
    }
    
    public void setLideres(ArrayList<Usuario> lideresProyecto){
        
        this.lideres = lideresProyecto;
        
        for(Usuario l:lideres){
             jComboBoxLideres.addItem(l.getNombre());   
        }
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxProyectos = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonProyecto = new javax.swing.JButton();
        jLabelItems = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelIntegrantes = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonVerItems = new javax.swing.JButton();
        jComboBoxLideres = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelCantidadItems = new javax.swing.JLabel();
        jLabelCantidadIntegrantes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 450));

        jComboBoxProyectos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBoxProyectos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--" }));
        jComboBoxProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProyectosActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Proyecto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 12))); // NOI18N

        jButtonProyecto.setText("Guardar");
        jButtonProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProyectoActionPerformed(evt);
            }
        });

        jLabelItems.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelItems.setText("Cantidad de Ítems");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre");

        jLabelIntegrantes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabelIntegrantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntegrantes.setText("Integrantes");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jButtonVerItems.setText("Items");
        jButtonVerItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerItemsActionPerformed(evt);
            }
        });

        jComboBoxLideres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBoxLideres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione para cambiar lider de proyecto" }));
        jComboBoxLideres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLideresActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Líder de Proyecto");

        jLabelCantidadItems.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabelCantidadIntegrantes.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVerItems, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLideres, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelItems))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCantidadItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelCantidadIntegrantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLideres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCantidadItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelItems, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIntegrantes, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabelCantidadIntegrantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProyecto)
                    .addComponent(jButtonVerItems))
                .addGap(38, 38, 38))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scrumban64.png"))); // NOI18N
        jLabel1.setText("Proyectos");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione un proyecto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProyectos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jComboBoxProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProyectosActionPerformed
        // TODO add your handling code here:
        int indexSeleccionado  = jComboBoxProyectos.getSelectedIndex();
        
         if (indexSeleccionado > 0){
                  String opcionSeleccionada = jComboBoxProyectos.getItemAt(indexSeleccionado);
                  proyectoSeleccionado = generadorProyectos.getProyecto(opcionSeleccionada);
                  jTextFieldNombre.setText(proyectoSeleccionado.getNombre());
                  jLabelCantidadItems.setText("" + proyectoSeleccionado.getItems().size());
                         
                           if(proyectoSeleccionado.getEquipo() == null){
                                     jLabelCantidadIntegrantes.setText("Sin Equipo");
                           }else{
                                     jLabelCantidadIntegrantes.setText("" + proyectoSeleccionado.getEquipo().getSize());
                           } 
                           
                  jButtonVerItems.setEnabled(true);     
                  
                           if(proyectoSeleccionado.getLider() == null){
                                    jComboBoxLideres.setSelectedIndex(0);
                           }else{
                                    jComboBoxLideres.setSelectedItem(proyectoSeleccionado.getLider().getNombre());
                           }
        }
        
    }//GEN-LAST:event_jComboBoxProyectosActionPerformed

    private void jButtonProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProyectoActionPerformed
         
         // TODO add your handling code here:
         boolean nombreModificado = false;
         boolean liderModificado = false;
         String nombreProyecto = (String)jComboBoxProyectos.getSelectedItem();
         String nuevoNombre = jTextFieldNombre.getText();
         
                  // primero se comprueba si el nombre puede cambiarse
                  if (!(nombreProyecto.equals(nuevoNombre))){
                           Proyecto otroProyecto = generadorProyectos.getProyecto(nuevoNombre);
                           if(otroProyecto != null){
                                    if (!(otroProyecto.equals(proyectoSeleccionado))){
                                             jTextFieldNombre.setText(nombreProyecto);
                                    } 
                                    else{                  
                                             proyectoSeleccionado.setNombre(nuevoNombre);
                                             nombreModificado = true;
                                    }
                           }else{
                                             proyectoSeleccionado.setNombre(nuevoNombre);
                                             nombreModificado = true;
                           }
                  }
                  
         Usuario nuevoLider =  generadorUsuarios.getUsuario((String)jComboBoxLideres.getSelectedItem());
         System.out.println("Index: " + jComboBoxLideres.getSelectedIndex());
                  if(jComboBoxLideres.getSelectedIndex()>0){
                           if (!(proyectoSeleccionado.getLider().equals(nuevoLider))){
                                    proyectoSeleccionado.setLider(nuevoLider);
                                    System.out.println("Nombre nuevo lider: " + nuevoLider.getNombre());
                                    jComboBoxLideres.setSelectedItem(nuevoLider.getNombre());
                                    liderModificado = true;
                           }
                  }
                                                     
                  if(nombreModificado & liderModificado){
                           JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Informacion modificada con éxito");
                  }else if(nombreModificado){
                           JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Nombre de proyecto modificado con éxito");
                           setProyectos(generadorProyectos.getProyectosAsArrayList());
                           jComboBoxProyectos.setSelectedItem(nuevoNombre);
                           jTextFieldNombre.setText(nuevoNombre);
                  }else if(liderModificado){
                           JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Líder modificado con éxito");
                  }else{
                           JOptionPane.showMessageDialog((JFrame)SwingUtilities.getWindowAncestor(this), "Informacion modificada con éxito");
                  }

    }//GEN-LAST:event_jButtonProyectoActionPerformed

    private void jButtonVerItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerItemsActionPerformed
        // TODO add your handling code here:
        /* se consigue el padre para pasarle el proyecto, 
           así desde el frame se cambia al panel de item con el proyecto seleccionado */
         FramePrincipal framePadre = (FramePrincipal)SwingUtilities.getWindowAncestor(this);
        /* el botón se habilita cuando se selecciona un proyecto, 
           por lo que no es necesario comprobar si hay un proyecto válido en la comboBoxProyectos*/
         proyectoSeleccionado= generadorProyectos.getProyecto((String)jComboBoxProyectos.getSelectedItem());
         framePadre.mostrarItems(proyectoSeleccionado);
        
                          
    }//GEN-LAST:event_jButtonVerItemsActionPerformed

    private void jComboBoxLideresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLideresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLideresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProyecto;
    private javax.swing.JButton jButtonVerItems;
    private javax.swing.JComboBox<String> jComboBoxLideres;
    private javax.swing.JComboBox<String> jComboBoxProyectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCantidadIntegrantes;
    private javax.swing.JLabel jLabelCantidadItems;
    private javax.swing.JLabel jLabelIntegrantes;
    private javax.swing.JLabel jLabelItems;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
